language: python
sudo: false

addons:
  apt:
    packages:
    - shellcheck

install:
 - pip3 install ply pycodestyle pylint pylint-quotes

script:
  - mkdir logs
  - pip3 install colorama
  - python3 scripts/lint/checkProjectStructure.py --text --dep-check-dir src --dep-check-dir extensions --dep-check-dir plugins --dest-dir logs
  - pushd scripts
  - pylint --rcfile .pylintrc --load-plugins pylint_quotes --output-format=parseable ./*/*.py
  - pycodestyle --config=.pycodestyle ./*/*.py
  - shellcheck --format=gcc ./*/*.sh
